export const ANIMATION_DURATION = Object.freeze({
  LINEAR_TRANSIION: 400,
  FADE_IN: 450,
  LINEAR_TRANSITION_DELAY: 50,
  LIST_ITEM_ANIMATION: {
    FADE_IN: 400,
    ITEM_ANIMATION_DELAY: 50,
  },
  TASK_STATUS: {
    CHECKBOX_ANIMATION: 400,
    TASK_MOVE_DELAY: 1500,
  },
});
